FROM python:3.9
MAINTAINER akeec
RUN mkdir /app
COPY . /app
WORKDIR /app
RUn ls
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN echo 'Hi, I am in your container'
EXPOSE 7000
#CMD ["python","/app/wdis_v1/app.py"]
CMD ["uvicorn","openapi_server.main:app","--host","0.0.0.0","--port","7000"]